/* eslint-disable */
/* global WebImporter */

// PARSER IMPORTS
import heroCutoutParser from './parsers/hero-cutout.js';
import columnsSpotlightParser from './parsers/columns-spotlight.js';
import columnsPromoParser from './parsers/columns-promo.js';
import cardsIconParser from './parsers/cards-icon.js';
import tabsPromoParser from './parsers/tabs-promo.js';
import captureVideoProps from './utils/brightcove-capture.js';
// source image URL (or data: hash) -> local content path; generated by localize-images.mjs
import LOCAL_IMAGES from './local-images.js';

// FNV-1a 32-bit; must match localize-images.mjs
function imageKey(src) {
  if (!src.startsWith('data:')) return src;
  let h = 0x811c9dc5;
  for (let i = 0; i < src.length; i += 1) {
    h = Math.imul(h ^ src.charCodeAt(i), 0x01000193) >>> 0;
  }
  return `data:${h.toString(16).padStart(8, '0')}`;
}

/**
 * Point images at local copies (content/images) so they are uploaded into AEM Assets.
 * Absolute source URLs and data: URIs are not ingested by the AEM upload.
 */
function localizeImages(main) {
  main.querySelectorAll('img[src]').forEach((img) => {
    const local = LOCAL_IMAGES[imageKey(img.getAttribute('src'))];
    if (local) img.setAttribute('src', `./${local}`);
  });
}
import columnsAdvisorParser from './parsers/columns-advisor.js';

// TRANSFORMER IMPORTS
import cleanupTransformer from './transformers/ameriprise-cleanup.js';
import sectionsTransformer from './transformers/ameriprise-sections.js';

// PAGE TEMPLATE CONFIGURATION - Embedded from page-templates.json
const PAGE_TEMPLATE = {
  name: 'home',
  description: 'Ameriprise homepage: hero, spotlights, promo panels, ratings highlights, resource tabs, advisor locator and disclosures',
  urls: [
    'https://www.ameriprise.com/',
  ],
  blocks: [
    {
      name: 'hero-cutout',
      instances: ['section.ComplexHero'],
    },
    {
      name: 'columns-spotlight',
      instances: ['.Spotlight-component .Spotlight > .Grid'],
    },
    {
      name: 'columns-promo',
      instances: ['.component-wrapper > .component-loaded > div > section.Promo-redesign'],
    },
    {
      name: 'cards-icon',
      instances: ['section.Categories .Categories-blocks'],
    },
    {
      name: 'tabs-promo',
      instances: ['.HorizontalTabs'],
    },
    {
      name: 'columns-advisor',
      instances: ['#advisor-locator'],
    },
  ],
  sections: [
    {
      id: 'rc2',
      name: 'hero',
      selector: ['.ComplexHero-container'],
      style: null,
      blocks: ['hero-cutout'],
      defaultContent: [],
    },
    {
      id: 'rc4',
      name: 'spotlights',
      selector: ['.Spotlight-component'],
      style: null,
      blocks: ['columns-spotlight'],
      defaultContent: [],
    },
    {
      id: 'rc5',
      name: 'time-award-promo',
      selector: ['.component-wrapper > .component-loaded > div > section.Promo-redesign:has(.u-bgColorStone)'],
      style: null,
      blocks: ['columns-promo'],
      defaultContent: [],
    },
    {
      id: 'rc6',
      name: 'top-ratings',
      selector: ['section.Categories'],
      style: null,
      blocks: ['cards-icon'],
      defaultContent: ['section.Categories .Content.u-paddingTop48'],
    },
    {
      id: 'rc7',
      name: 'retirement-quiz-promo',
      selector: ['.component-wrapper > .component-loaded > div > section.Promo-redesign:has(.u-bgColorPurpleLight10)'],
      style: null,
      blocks: ['columns-promo'],
      defaultContent: [],
    },
    {
      id: 'rc8',
      name: 'insights-tabs',
      selector: ['.component-wrapper:has(.HorizontalTabs)'],
      style: null,
      blocks: ['tabs-promo'],
      defaultContent: ['.component-wrapper:has(.HorizontalTabs) > section > header'],
    },
    {
      id: 'rc9',
      name: 'advisor-locator',
      selector: ['#advisor-locator'],
      style: null,
      blocks: ['columns-advisor'],
      defaultContent: [],
    },
    {
      id: 'rc11',
      name: 'disclosures',
      selector: ['section.SimpleContent'],
      style: 'disclaimer',
      blocks: [],
      defaultContent: ['section.SimpleContent .Content.content-block'],
    },
  ],
};

// PARSER REGISTRY
const parsers = {
  'hero-cutout': heroCutoutParser,
  'columns-spotlight': columnsSpotlightParser,
  'columns-promo': columnsPromoParser,
  'cards-icon': cardsIconParser,
  'tabs-promo': tabsPromoParser,
  'columns-advisor': columnsAdvisorParser,
};

// TRANSFORMER REGISTRY - cleanup first, then section breaks/metadata
const transformers = [
  cleanupTransformer,
  ...(PAGE_TEMPLATE.sections && PAGE_TEMPLATE.sections.length > 1 ? [sectionsTransformer] : []),
];

/**
 * Execute all page transformers for a specific hook
 * @param {string} hookName - 'beforeTransform' or 'afterTransform'
 * @param {Element} element - The DOM element to transform
 * @param {Object} payload - { document, url, html, params }
 */
function executeTransformers(hookName, element, payload) {
  const enhancedPayload = {
    ...payload,
    template: PAGE_TEMPLATE,
  };

  transformers.forEach((transformerFn) => {
    try {
      transformerFn.call(null, hookName, element, enhancedPayload);
    } catch (e) {
      console.error(`Transformer failed at ${hookName}:`, e);
    }
  });
}

/**
 * Find all blocks on the page based on the embedded template configuration
 * @param {Document} document - The DOM document
 * @param {Object} template - The embedded PAGE_TEMPLATE object
 * @returns {Array} Block instances found on the page
 */
function findBlocksOnPage(document, template) {
  const pageBlocks = [];

  template.blocks.forEach((blockDef) => {
    blockDef.instances.forEach((selector) => {
      const elements = document.querySelectorAll(selector);
      if (elements.length === 0) {
        console.warn(`Block "${blockDef.name}" selector not found: ${selector}`);
      }
      elements.forEach((element) => {
        pageBlocks.push({
          name: blockDef.name,
          selector,
          element,
          section: blockDef.section || null,
        });
      });
    });
  });

  console.log(`Found ${pageBlocks.length} block instances on page`);
  return pageBlocks;
}

export default {
  // Runs on the live page before html2md rebuilds the DOM (React props still available)
  onLoad: async ({ document }) => {
    try {
      captureVideoProps(document);
    } catch (e) {
      console.warn('captureVideoProps failed:', e);
    }
  },

  transform: (payload) => {
    const { document, url, params } = payload;

    const main = document.body;

    // 1. Initial cleanup + section break markers
    executeTransformers('beforeTransform', main, payload);

    // 2. Find blocks on page using embedded template
    const pageBlocks = findBlocksOnPage(document, PAGE_TEMPLATE);

    // 3. Parse each block (skip elements already replaced by an earlier parser)
    pageBlocks.forEach((block) => {
      if (!block.element.parentNode) return;
      const parser = parsers[block.name];
      if (parser) {
        try {
          parser(block.element, { document, url, params });
        } catch (e) {
          console.error(`Failed to parse ${block.name} (${block.selector}):`, e);
        }
      } else {
        console.warn(`No parser found for block: ${block.name}`);
      }
    });

    // 4. Final cleanup + section metadata
    executeTransformers('afterTransform', main, payload);

    // 5. WebImporter built-in rules
    const hr = document.createElement('hr');
    main.appendChild(hr);
    WebImporter.rules.createMetadata(main, document);
    WebImporter.rules.transformBackgroundImages(main, document);
    WebImporter.rules.adjustImageUrls(main, url, params.originalURL);
    localizeImages(main);

    // 6. Sanitized path (homepage maps to /index)
    const rawPath = new URL(params.originalURL).pathname
      .replace(/\/$/, '')
      .replace(/\.html?$/, '');
    const path = WebImporter.FileUtils.sanitizePath(rawPath === '' ? '/index' : rawPath);

    return [{
      element: main,
      path,
      report: {
        title: document.title,
        template: PAGE_TEMPLATE.name,
        blocks: pageBlocks.map((b) => b.name),
      },
    }];
  },
};
