/* eslint-disable */
/**
 * Localize page images for AEM (xwalk) uploads.
 *
 * Images referenced by absolute source URLs (or inline data: URIs) are not ingested
 * into AEM Assets on upload, so they render broken in Universal Editor. This tool:
 *   1. scans content/*.plain.html (excluding nav/footer) for <img> sources,
 *   2. saves each image into content/images/,
 *   3. writes tools/importer/local-images.js — a map the import script applies after
 *      WebImporter.rules.adjustImageUrls so imported pages reference images/<file>.
 *
 * Re-run after changing parsers or adding pages, then re-bundle and re-import:
 *   node tools/importer/localize-images.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../..');
const CONTENT = path.join(ROOT, 'content');
const IMAGES = path.join(CONTENT, 'images');
const MAP_FILE = path.join(ROOT, 'tools/importer/local-images.js');

// FNV-1a 32-bit — must match imageKey() in import-home.js (runs synchronously in the browser)
const fnv1a = (str) => {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i += 1) {
    // eslint-disable-next-line no-bitwise
    h = Math.imul(h ^ str.charCodeAt(i), 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
};
export const imageKey = (src) => (src.startsWith('data:') ? `data:${fnv1a(src)}` : src);

const EXT = { 'image/svg+xml': 'svg', 'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp', 'image/gif': 'gif' };

function fileNameFor(src, mime) {
  const hash = crypto.createHash('sha1').update(src).digest('hex').slice(0, 8);
  if (src.startsWith('data:')) return `icon-${hash}.${EXT[mime] || 'svg'}`;
  const parts = decodeURIComponent(new URL(src).pathname).split('/').filter(Boolean);
  const named = parts.reverse().find((p) => /\.(png|jpe?g|gif|webp|svg)$/i.test(p)) || parts[parts.length - 1] || 'image';
  const base = named.toLowerCase().replace(/\.[a-z0-9]+$/, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
  const ext = (named.match(/\.([a-z0-9]+)$/i) || [])[1]?.toLowerCase().replace('jpeg', 'jpg') || EXT[mime] || 'jpg';
  return `${base}-${hash}.${ext}`;
}

async function saveImage(src) {
  if (src.startsWith('data:')) {
    const [, mime, b64, data] = src.match(/^data:([^;,]+)(;base64)?,(.*)$/s) || [];
    const buf = b64 ? Buffer.from(data, 'base64') : Buffer.from(decodeURIComponent(data));
    const file = fileNameFor(src, mime);
    fs.writeFileSync(path.join(IMAGES, file), buf);
    return file;
  }
  const resp = await fetch(src, { headers: { 'User-Agent': 'Mozilla/5.0 (excat image localizer)' } });
  if (!resp.ok) throw new Error(`${resp.status} ${src}`);
  const mime = (resp.headers.get('content-type') || '').split(';')[0];
  if (!mime.startsWith('image/')) throw new Error(`not an image (${mime}) ${src}`);
  const file = fileNameFor(src, mime);
  fs.writeFileSync(path.join(IMAGES, file), Buffer.from(await resp.arrayBuffer()));
  return file;
}

const existing = fs.existsSync(MAP_FILE)
  ? JSON.parse(fs.readFileSync(MAP_FILE, 'utf8').replace(/^[\s\S]*?export default\s*/, '').replace(/;\s*$/, ''))
  : {};
const map = { ...existing };
fs.mkdirSync(IMAGES, { recursive: true });

const pages = fs.readdirSync(CONTENT).filter((f) => f.endsWith('.plain.html') && !/^(nav|footer)\./.test(f));
const sources = new Set();
pages.forEach((f) => {
  const html = fs.readFileSync(path.join(CONTENT, f), 'utf8');
  [...html.matchAll(/<img[^>]*\ssrc="([^"]+)"/g)].forEach(([, src]) => {
    const s = src.replace(/&amp;/g, '&');
    if (/^(https?:|data:)/.test(s)) sources.add(s);
  });
});

let failures = 0;
for (const src of sources) {
  const key = imageKey(src);
  if (map[key] && fs.existsSync(path.join(CONTENT, map[key]))) continue;
  try {
    map[key] = `images/${await saveImage(src)}`;
    console.log(`saved ${map[key]}  <-  ${src.slice(0, 90)}`);
  } catch (e) {
    failures += 1;
    console.error(`FAILED ${e.message}`);
  }
}

fs.writeFileSync(MAP_FILE, `/* Generated by tools/importer/localize-images.mjs — source image URL (or data: hash) -> local content path */\nexport default ${JSON.stringify(map, null, 2)};\n`);
console.log(`${Object.keys(map).length} images mapped (${failures} failed) -> ${path.relative(ROOT, MAP_FILE)}`);
process.exitCode = failures ? 1 : 0;
