/* Generated by tools/importer/localize-images.mjs — source image URL (or data: hash) -> local content path */
export default {
  "https://www.ameriprise.com/binaries/content/gallery/ampcom/heros/redesign-heroes/gettyimages-513478544_cmyk_flipped.png": "images/gettyimages-513478544-cmyk-flipped-38f24f72.png",
  "data:d06fdb47": "images/icon-a0219bc1.svg",
  "data:51cd92fe": "images/icon-e2d80e4d.svg",
  "https://www.ameriprise.com/binaries/content/gallery/ampcom/most-iconic.jpg": "images/most-iconic-4ceae5aa.jpg",
  "data:221d55e8": "images/icon-400bb5de.svg",
  "data:6297d81e": "images/icon-e31869b7.svg",
  "data:55a426e2": "images/icon-c3b6f8d1.svg",
  "https://www.ameriprise.com/binaries/content/gallery/ampcom/retirement-profiles_gettyimages-1168316582_resize.jpg": "images/retirement-profiles-gettyimages-1168316582-resize-32fa8a0e.jpg",
  "https://cf-images.us-east-1.prod.boltdns.net/v1/static/1625296066001/95313529-11c4-4fa2-a6c5-6fd77040878b/550fde03-79f1-4317-8233-f97c8df3d2da/1280x720/match/image.jpg": "images/image-0fc184d0.jpg",
  "https://www.ameriprise.com/binaries/content/gallery/ampcom/mobile-and-tablet-secure-site-view_ampcom-hp.png": "images/mobile-and-tablet-secure-site-view-ampcom-hp-ab19789d.png",
  "https://www.ameriprise.com/binaries/content/gallery/ampcom/gettyimages-691047203_homepage-security.jpg": "images/gettyimages-691047203-homepage-security-5ee59736.jpg",
  "data:3de4f681": "images/icon-468c86c5.svg",
  "https://www.ameriprise.com/binaries/content/gallery/ampcom/ameriprise-social-image.png/ameriprise-social-image.png/brxp%3Alarge": "images/ameriprise-social-image-44d5e9d4.png"
};
